### ISSUE TITLE
Struggling to add WKT polygons

### ISSUE THREAD

**Issue by GaryClutterbuck** [jamesdales/IconMapSupport#10]
Hi James
I've been trying to create an iconmap using WKT polygons.  I've converted the shapefile containing all the LSOAs into WKT values, using either QGIS or https://mygeodata.cloud/

I've added an Index column and put that into the category column, and added  a custom value column (containing values of 1) into the size field, then in Objects, I've clicked on the Image/WKT fx button and tried adding in the WKT column which contains a polygon in each record.  

As soon as I add the WKT column to the map, it zooms out to show the entire world, rather than zooming in on the LSOAs stored in my file.  Can you let me know where I'm going wrong, please?

I've added a PBIX file to demonstrate.
[Gary_WKT.zip](https://github.com/jamesdales/IconMapSupport/files/12051366/Gary_WKT.zip)
[Gary_WKT.zip](https://github.com/jamesdales/IconMapSupport/files/12051367/Gary_WKT.zip)

**Comment by jamesdales** [comment]
Hi @GaryClutterbuck 

I think it's down to the coordinate system your WKT polygons are using? I think it looks like British National Grid, rather than WGS 84. 


When exporting your shapes from QGIS, if you change the CRS to EPSG:4326 - WGS 84, then your polygons should render. 
[Gary_WKT_4326.zip](https://github.com/jamesdales/IconMapSupport/files/12067095/Gary_WKT_4326.zip). See the attached file. 

Icon Map can support BNG, but it requires a map background that uses the EPSG:2770 projection (such as those used by Ordnance Survey).

Thanks

James

**Comment by GaryClutterbuck** [comment]
Hi James
Thank you very much for clarifying what was causing the issue.  After I'd posted the query, I found another file I'd created some time ago with a WKT column that mapped perfectly, but I was unable to figure out why the file I posted online here wasn't working.  Your explanation makes perfect sense, and is greatly appreciated.  Thanks also for responding so quickly.

Best wishes
Gary
