### ISSUE TITLE
WMS layer not Shown

### ISSUE THREAD

**Issue by sujit3239** [jamesdales/IconMapSupport#46]
Hi team we are not able to Plot wms layer in Icon map through Power Bi,Please check

**Comment by jamesdales** [comment]
Hi. Could you provide more information about your WMS server and the URL you are using?

**Comment by nahles** [comment]
Hi James,

I'm also running into this issue.

Full URL: https://fwspublicservices.wim.usgs.gov/wetlandsmapservice/services/Wetlands/MapServer/WMSServer?request=GetCapabilities&service=WMS

URL I'm using in Icon Map: https://fwspublicservices.wim.usgs.gov/wetlandsmapservice/services/Wetlands/MapServer/WMSServer?

Name Tag: Wetlands

Thanks, appreciate all your hard work on this!
Noah

**Comment by jamesdales** [comment]
Hi

I've managed to get this working:

![image](https://github.com/jamesdales/IconMapSupport/assets/37669155/3b7f6c93-f4ee-468a-8976-fb71ead94997)

You were using the correct URL: 
https://fwspublicservices.wim.usgs.gov/wetlandsmapservice/services/Wetlands/MapServer/WMSServer?

But the layer name in the GetCapabilities response is 1, rather than Wetlands, as it uses the name, not the title:

![image](https://github.com/jamesdales/IconMapSupport/assets/37669155/0d165863-20bc-4770-adfa-d13a42c45136)

So setting the WMS Layer Name property to 1 should display your map.

Thanks

James

**Comment by nahles** [comment]
Thanks so much!
